<?php

/**
 * @file
 * Demonstrates common ways of interacting with the entity system
 */

/**
 * Implements hook_menu()
 */
function entitydemo_menu() {
  $items = array();

  $items['demo'] = array(
    'title' => 'Entity Demos',
    'description' => 'List of entity demo\'s provided by this module',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_demo',
    'menu_name' => 'navigation',
    'file' => 'includes/entitydemo.demo.inc',
  );

  $items['demo/1'] = array(
    'title' => 'Entity Load Demos',
    'description' => 'Demonstration of usinf entity functions to interact with entities in core',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_demo1',
    'menu_name' => 'navigation',
    'file' => 'includes/entitydemo.demo1.inc',
  );

  $items['demo/2'] = array(
    'title' => 'EntityFieldQuery',
    'description' => 'Demonstrates using EntityFieldQuery to find data',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_demo2',
    'menu_name' => 'navigation',
    'file' => 'includes/entitydemo.demo2.inc',
  );

  return $items;
}
